spring.application.name=attendance
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance
spring.datasource.username=postgres
spring.datasource.password=f31272564

mybatis.configuration.map-underscore-to-camel-case=true