spring.application.name=attendance
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

mybatis.configuration.map-underscore-to-camel-case=true